# Generated by Django 4.2.2 on 2023-06-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(default="name", max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
